baseURL = "https://erlonbie.github.io/slides"
title = "Erlon Bié"
theme = ["github.com/dzello/reveal-hugo"]
contentDir = "content/slides"
publishDir = "public/slides"
staticDir = "static/slides"

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
